import { generateJestFiles, routeToFilename } from "../jest-writer"
import type { TestCase } from "../../generator/types"

// ── routeToFilename ───────────────────────────────────────────────────────────

describe("routeToFilename", () => {
  it("converts simple route to filename", () => {
    expect(routeToFilename("POST /users")).toBe("post_users.spec.ts")
  })

  it("converts route with nested path", () => {
    expect(routeToFilename("GET /api/v1/users")).toBe("get_api_v1_users.spec.ts")
  })

  it("converts route with path param", () => {
    expect(routeToFilename("DELETE /users/:id")).toBe("delete_users_id.spec.ts")
  })

  it("handles extra slashes and special chars gracefully", () => {
    const result = routeToFilename("PATCH /orgs/:orgId/members")
    expect(result).toBe("patch_orgs_orgid_members.spec.ts")
  })
})

// ── generateJestFiles ─────────────────────────────────────────────────────────

const happyCase: TestCase = {
  id:             "post_users_happy_1",
  route:          "POST /users",
  method:         "POST",
  path:           "/users",
  category:       "happy_path",
  description:    "POST /users — valid payload",
  payload:        { email: "test@example.com", name: "Alice" },
  headers:        { "Content-Type": "application/json" },
  expectedStatus: 201,
}

const invalidCase: TestCase = {
  id:             "post_users_invalid_format_email_2",
  route:          "POST /users",
  method:         "POST",
  path:           "/users",
  category:       "invalid_format",
  description:    "POST /users — email: invalid format",
  payload:        { email: "not-an-email", name: "Alice" },
  headers:        { "Content-Type": "application/json" },
  expectedStatus: 400,
}

const noAuthCase: TestCase = {
  id:             "auth_no_token_post_users_3",
  route:          "POST /users",
  method:         "POST",
  path:           "/users",
  category:       "no_auth",
  description:    "POST /users — no auth token → expect 401",
  headers:        {},
  expectedStatus: 401,
}

describe("generateJestFiles", () => {
  it("returns one file per unique route", () => {
    const files = generateJestFiles([happyCase, invalidCase])
    expect(files.size).toBe(1)
    expect([...files.keys()]).toContain("post_users.spec.ts")
  })

  it("produces separate files for different routes", () => {
    const getCase: TestCase = {
      ...happyCase,
      id:     "get_users_happy",
      route:  "GET /users",
      method: "GET",
      path:   "/users",
      payload: undefined,
      expectedStatus: 200,
    }
    const files = generateJestFiles([happyCase, getCase])
    expect(files.size).toBe(2)
  })

  it("generated file contains describe block with route", () => {
    const files = generateJestFiles([happyCase])
    const content = files.get("post_users.spec.ts")!
    expect(content).toContain('describe("POST /users"')
  })

  it("generated file contains it block with description", () => {
    const files = generateJestFiles([happyCase])
    const content = files.get("post_users.spec.ts")!
    expect(content).toContain("POST /users — valid payload")
    expect(content).toContain("expect(res.status).toBe(201)")
  })

  it("generated file uses API_BASE_URL env var", () => {
    const files = generateJestFiles([happyCase])
    const content = files.get("post_users.spec.ts")!
    expect(content).toContain('process.env["API_BASE_URL"]')
  })

  it("uses custom defaultBaseUrl in generated file", () => {
    const files = generateJestFiles([happyCase], { defaultBaseUrl: "http://api.example.com" })
    const content = files.get("post_users.spec.ts")!
    expect(content).toContain("http://api.example.com")
  })

  it("generates fetch call with body for POST", () => {
    const files = generateJestFiles([happyCase])
    const content = files.get("post_users.spec.ts")!
    expect(content).toContain("JSON.stringify(")
    expect(content).toContain('"email"')
  })

  it("generates fetch call without body for no_auth case (no payload)", () => {
    const files = generateJestFiles([noAuthCase])
    const content = files.get("post_users.spec.ts")!
    expect(content).toContain("expect(res.status).toBe(401)")
    expect(content).not.toContain("JSON.stringify")
  })

  it("includes generated-by banner comment", () => {
    const files = generateJestFiles([happyCase], { generatedBy: "archtest generate" })
    const content = files.get("post_users.spec.ts")!
    expect(content).toContain("Generated by archtest generate")
  })

  it("returns empty map for empty input", () => {
    const files = generateJestFiles([])
    expect(files.size).toBe(0)
  })
})
