import type { TestCase } from "../generator/types"

export interface JestWriterOptions {
  /** e.g. "http://localhost:3000" — used as default in generated file */
  defaultBaseUrl?: string
  /** Banner comment at top of file */
  generatedBy?: string
}

/**
 * Groups test cases by route and emits one Jest describe block per route.
 * Returns a map of filename → file content.
 */
export function generateJestFiles(
  cases: TestCase[],
  opts: JestWriterOptions = {}
): Map<string, string> {
  const byRoute = groupByRoute(cases)
  const files   = new Map<string, string>()

  for (const [route, routeCases] of byRoute) {
    const filename = routeToFilename(route)
    const content  = renderFile(route, routeCases, opts)
    files.set(filename, content)
  }

  return files
}

// ── Grouping ─────────────────────────────────────────────────────────────────

function groupByRoute(cases: TestCase[]): Map<string, TestCase[]> {
  const map = new Map<string, TestCase[]>()
  for (const c of cases) {
    if (!map.has(c.route)) map.set(c.route, [])
    map.get(c.route)!.push(c)
  }
  return map
}

// ── Filename ──────────────────────────────────────────────────────────────────

export function routeToFilename(route: string): string {
  // "POST /api/users/:id" → "post_api_users_id.spec.ts"
  return route
    .toLowerCase()
    .replace(/[^a-z0-9/]/g, "_")
    .replace(/\//g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "") + ".spec.ts"
}

// ── File rendering ────────────────────────────────────────────────────────────

function renderFile(
  route: string,
  cases: TestCase[],
  opts: JestWriterOptions
): string {
  const baseUrl   = opts.defaultBaseUrl ?? "http://localhost:3000"
  const generated = opts.generatedBy    ?? "archtest generate"
  const banner    = [
    `// Generated by ${generated} — do not edit manually`,
    `// Route: ${route}`,
    "",
  ].join("\n")

  const [method, path] = splitRoute(route)

  const describe = [
    `describe("${route}", () => {`,
    `  const BASE_URL = process.env["API_BASE_URL"] ?? "${baseUrl}"`,
    `  const PATH = "${path}"`,
    "",
    cases.map(c => renderTest(c, method)).join("\n\n"),
    "})",
  ].join("\n")

  return `${banner}\n${describe}\n`
}

function renderTest(c: TestCase, _method: string): string {
  const lines: string[] = []
  lines.push(`  it(${JSON.stringify(c.description)}, async () => {`)

  const fetchArgs = buildFetchArgs(c)
  lines.push(`    const res = await fetch(\`\${BASE_URL}\${PATH}\`, ${fetchArgs})`)
  lines.push(`    expect(res.status).toBe(${c.expectedStatus})`)
  lines.push("  })")

  return lines.join("\n")
}

function buildFetchArgs(c: TestCase): string {
  const opts: Record<string, unknown> = {
    method: c.method,
  }

  if (Object.keys(c.headers).length > 0) {
    opts["headers"] = c.headers
  }

  if (c.payload !== undefined) {
    opts["body"] = "__BODY_PLACEHOLDER__"
  }

  let json = JSON.stringify(opts, null, 4)
    .replace(/"__BODY_PLACEHOLDER__"/, `JSON.stringify(${JSON.stringify(c.payload, null, 0)})`)

  // indent inner lines to match 4-space block inside it()
  json = json.split("\n").map((line, i) => (i === 0 ? line : "    " + line)).join("\n")

  return json
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function splitRoute(route: string): [string, string] {
  const space = route.indexOf(" ")
  if (space === -1) return [route, "/"]
  return [route.slice(0, space), route.slice(space + 1)]
}
